alias ls='ls -al'
alias source='cd c:; cd source'

alias bitbucket='source; cd bitbucket'
alias github='source; cd github'
alias solution='bitbucket; cd ao.website.sales'
alias sales='solution'
alias website='solution'
alias frontend='bitbucket; cd ao.frontend.assets'
alias fe='frontend'
alias checkout='bitbucket; cd ao.checkout'
alias workspace='source; cd workspace'
alias me='workspace'

alias vimbash='cd ~; vim .bash_profile'
